name: demand-allocator-full
channels:
  - conda-forge
dependencies:
  - python=3.10
  # ───◀ FastAPI & web
  - fastapi=0.100.0
  - uvicorn=0.32.0
  - jinja2=3.1.4
  - python-multipart=0.0.12
  - requests=2.32.3
  - pydantic=2.10.6
  - pydantic-settings=2.7.1
  - passlib=1.7.4
  # ───◀ Data wrangling & EDA pesada
  - geopandas
  - pandas
  - numpy
  - unidecode
  - geopy
  - libpysal
  - osmnx
  - pandana
  - matplotlib
  - reportlab
  - weasyprint=62.3
  - plotly=5.24.1
  # ───◀ Interface de mapas
  - pip
  - pip:
      - keplergl==0.3.2
